### ISSUE TITLE
How to specify Remote Addr/Port in gus_handle_msg ?

### ISSUE THREAD

**Issue by lc3t35** [andrewtj/gen_udp_sketch#1]
Hi,
I would like to specify the {RemoteIP, RemotePort} in
````
gus_handle_msg(_Ref, Socket, _LocalAddr, {RemoteIP, RemotePort}, Msg)
````
I was unable to find the way with the current documentation ;) Is it when we launch ?
````
gus:start_link([{module,gus_echo},{ip,{127,0,0,1}},{port,5030}]).
````
Thank you for your help.

**Comment by andrewtj** [comment]
I've paged-out Erlang so my assistance here will be a bit limited.

I take it you're wanting to use this code for a client. As this code was intended to demonstrate implementing a server it doesn't expose the socket except in the callback.

To do what you've asked, you'd need to modify it to expose the socket to something that will initiate the session (by sending a message to `{RemoteIP, RemotePort}` via `gen_udp:send/4`).

However it's highly likely you'll need to make further changes to make it suitable to the task you have in mind, so it'd probably be better to use it as an echo server against which to write your own client library.

**Comment by lc3t35** [comment]
Thank you for your answer anyway, we can close then.
